# hello-gateway-config

server:
  port: 8085

eureka:
instance:
  hostname:localhost
client:
  service-url: https://github.com/ZEFFERSKIOICH/hello-config-repo.git
    default-zone: http://localhost:8761/hello-eureka-service

spring:
  application:
    name: hello-gateway
  cloud:
    gateway:
      routes:
        - id: hello-consumer
          uri: lb://hello-consumer
          predicates:
            - Path=/helloc/**
        - id: hello-producer
          uri: lb://hello-producer
          predicates:
            - Path=/hellop/**
